# Permitir conexiones sin contraseña (solo apra el desarrollo)
allow_anonymous true

# Listener estándar MQTT (Para la Raspberry Pi y Backend en Python)
listener 1883 0.0.0.0

# Listener para WebSockets (Para el dashboard del Frontend)
listener 9001
protocol websockets

# Habilitar persistencia de mensajes
persistence true
persistence_location /mosquitto/data/

# Configuración de logs
log_dest file /mosquitto/log/mosquitto.log
